Move entropy_src modules to UHDM
antmicro/verilator-old-archived pull request #366
Opened 2021-07-02 13:34 UTC by kbieganski

Move remaining `entropy_src` modules to UHDM.

2021-08-06 16:40 UTC, kbieganski commented
The change to module handling in this PR is that we don't clone and rename a module whenever we encounter a module instance. This allows the SV parser to use the modules loaded from UHDM (as long as they are not parametrized).

Unfortunately, parametrized modules can't be supported this way, so I decided the best way to handle those is to just readd them to the SV frontend arguments.

The change related to imported params forced me to add the `lint_off` to Ibex. Unfortunately, that was needed to handle parameters imported from packages imported from other packages.

2021-08-16 12:06 UTC, rkapuscik requested changes
Looks good, thanks! I like that you were able to get rid of the `partial_modules`.  The VAR_HIDDEN in Ibex is unfortunate, but I'm not sure if we can do anything about it with how imports are handled in UHDM.

2021-08-16 12:06 UTC, rkapuscik commented on src/UhdmAst.cpp
> +        auto it = shared.package_map.find(objectName); // In case it has been created becasue of an import
Typo in comment.

2021-08-16 12:06 UTC, rkapuscik commented on src/UhdmAst.cpp
> +                        module->user1(true); // Need to set params, mark as partial again
We could free and `break` here on first passing parameter.

2021-08-16 12:06 UTC, rkapuscik commented on uhdm-tests/opentitan/Makefile.in
> +READD=../src/lowrisc_prim_generic_clock_gating_0/rtl/prim_generic_clock_gating.sv \
As discussed, please change this to a burn-down list for the frontends to avoid listing files twice.

2021-08-17 06:09 UTC, rkapuscik approved these changes

2021-08-17 06:25 UTC, merged